# Generated by Django 5.2.8 on 2025-11-18 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='Fully qualified domain name of the compute node')),
                ('description', models.TextField(blank=True, verbose_name='Description of the compute node')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Physical location in datacenter')),
            ],
        ),
        migrations.CreateModel(
            name='DataCollectionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=255, unique=True, verbose_name='Activity identifier')),
                ('activity_type', models.CharField(max_length=128, verbose_name="Type of activity (e.g., 'Data Collection')")),
                ('start_time', models.DateTimeField(verbose_name='Activity start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Activity end time')),
                ('description', models.TextField(verbose_name='Description of the activity')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.CharField(max_length=255, unique=True, verbose_name='Unique dataset identifier (UUID)')),
                ('title', models.CharField(max_length=512, verbose_name='Dataset title')),
                ('description', models.TextField(verbose_name='Dataset description')),
                ('start_date', models.DateTimeField(verbose_name='Start of data collection period')),
                ('end_date', models.DateTimeField(verbose_name='End of data collection period')),
                ('issued', models.DateField(auto_now_add=True, verbose_name='Publication date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last modification date')),
                ('license_name', models.CharField(default='Creative Commons Attribution 4.0 International', max_length=255, verbose_name='License name')),
                ('license_url', models.URLField(default='https://creativecommons.org/licenses/by/4.0/', verbose_name='License URL')),
                ('creator_name', models.CharField(max_length=255, verbose_name='Dataset creator name')),
                ('creator_email', models.EmailField(max_length=254, verbose_name='Dataset creator email')),
                ('publisher_name', models.CharField(default='Area Science Park', max_length=255, verbose_name='Publisher name')),
                ('keywords', models.TextField(verbose_name='Comma-separated keywords')),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CPU', 'CPU Usage'), ('LINUX_CPU', 'Linux CPU Frequency/Thermal'), ('MEMORY', 'Memory'), ('DISK_IO', 'Disk I/O'), ('NETWORK', 'Network'), ('INFINIBAND', 'InfiniBand'), ('SMART_DEVICE', 'SMART Device Health'), ('SMART_ATTR', 'SMART Attributes'), ('IPMI', 'IPMI Sensor'), ('PROCSTAT', 'Process Statistics'), ('TURBOSTAT', 'Turbostat')], max_length=32, unique=True, verbose_name='Sensor type name')),
                ('description', models.TextField(verbose_name='Description of what this sensor type measures')),
                ('sosa_uri', models.URLField(blank=True, verbose_name='SOSA/SSN ontology URI for this sensor type')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=255, unique=True, verbose_name='Agent identifier')),
                ('name', models.CharField(max_length=255, verbose_name='Agent name')),
                ('agent_type', models.CharField(choices=[('SOFTWARE', 'Software Agent'), ('PERSON', 'Person'), ('ORGANIZATION', 'Organization')], max_length=32, verbose_name='Type of agent')),
                ('version', models.CharField(blank=True, max_length=64, verbose_name='Version (for software agents)')),
                ('description', models.TextField(blank=True, verbose_name='Agent description')),
                ('homepage', models.URLField(blank=True, verbose_name='Homepage URL')),
                ('activities', models.ManyToManyField(related_name='agents', to='fairdatacenter.datacollectionactivity', verbose_name='Activities associated with this agent')),
            ],
        ),
        migrations.AddField(
            model_name='datacollectionactivity',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='fairdatacenter.monitoringdataset', verbose_name='Associated dataset'),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=255, unique=True, verbose_name='Unique sensor identifier (UUID or URI)')),
                ('device_name', models.CharField(blank=True, max_length=128, verbose_name="Device name (e.g., 'sda', 'eth0', 'cpu0')")),
                ('interface_name', models.CharField(blank=True, max_length=128, verbose_name="Network interface name (e.g., 'bond0', 'ibp59s0')")),
                ('description', models.TextField(blank=True, verbose_name='Additional sensor description')),
                ('compute_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='fairdatacenter.computenode', verbose_name='Compute node where sensor is deployed')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fairdatacenter.sensortype', verbose_name='Type of sensor')),
            ],
        ),
        migrations.CreateModel(
            name='ObservableProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=128, unique=True, verbose_name='Name of the observable property')),
                ('label', models.CharField(max_length=255, verbose_name='Human-readable label')),
                ('description', models.TextField(verbose_name='Description of the property')),
                ('unit', models.CharField(max_length=64, verbose_name='Unit of measurement (e.g., percent, bytes, hertz)')),
                ('qudt_unit_uri', models.URLField(blank=True, verbose_name='QUDT ontology URI for the unit')),
                ('data_type', models.CharField(choices=[('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('BOOLEAN', 'Boolean'), ('STRING', 'String')], max_length=32, verbose_name='Data type of measurements')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observable_properties', to='fairdatacenter.sensortype', verbose_name='Sensor type that observes this property')),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('file_format', models.CharField(choices=[('CSV', 'CSV'), ('PARQUET', 'Parquet'), ('JSON', 'JSON')], default='CSV', max_length=32, verbose_name='File format')),
                ('media_type', models.CharField(default='text/csv', max_length=128, verbose_name='MIME type')),
                ('file_path', models.CharField(max_length=512, verbose_name='Path to file')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File size in bytes')),
                ('row_count', models.BigIntegerField(blank=True, null=True, verbose_name='Number of rows')),
                ('description', models.TextField(blank=True, verbose_name='File description')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='fairdatacenter.monitoringdataset', verbose_name='Parent dataset')),
                ('sensor_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fairdatacenter.sensortype', verbose_name='Sensor type contained in this file')),
            ],
        ),
    ]
